INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id) VALUES ('Tuxedo', 20, 'tuxedo.png', 3, true, 'Cleveland, OH', 1);
INSERT INTO fint.user (name, password, username) VALUES ('Kyle the Seller', 'KylePassword', 'KyleUsername');
INSERT INTO fint.user (name, password, username) VALUES ('Jason the Reviewer', 'JasonPassword', 'JasonUsername');
INSERT INTO fint.user (name, password, username) VALUES ('Jess the Reviewer', 'JessPassword', 'JessUsername');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (1, 2, 'This tuxedo is awesome', 4, '2019-11-07T16:24:29.000');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (1, 3, 'This tuxedo is terrible', 1, '2019-11-07T16:24:29.000');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (4, 3, 'This grill and tool is good', 4, '2019-11-07T16:24:29.000');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (5, 3, 'Comes with lots of charcoal', 5, '2019-11-07T16:24:29.000');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (6, 3, 'Brush cleaned well', 3, '2019-11-07T16:24:29.000');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (7, 3, 'Cover kept food warm', 4, '2019-11-07T16:24:29.000');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (8, 3, 'Grill was not new', 1, '2019-11-07T16:24:29.000');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (9, 3, 'Broke', 2, '2019-11-07T16:24:29.000');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (10, 3, 'grilling', 3, '2019-11-07T16:24:29.000');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (11, 3, 'twogrills', 2, '2019-11-07T16:24:29.000');
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id, post_date) VALUES ('Car', 300, 'car.png', 120, true, 'Akron, OH', 4, '1 11 2019');
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id, post_date) VALUES ('Basketball', 5, 'bball.png', 15, true, 'Seattle, WA', 5, '2 11 2019');
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id, post_date) VALUES ('Grill and Tool', 20, 'grillandtool.png', 13, true, 'Redmond, WA', 6, '3 11 2019');
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id, post_date) VALUES ('Grill and Charcoal', 25, 'grillandcharcoal.png', 13, true, 'Redmond, WA', 6, '4 11 2019');
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id, post_date) VALUES ('Grill Brush', 5, 'grillbrush.png', 13, true, 'Redmond, WA', 6, '5 11 2019');
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id, post_date) VALUES ('Grill Cover', 6, 'grillcover.png', 13, true, 'Redmond, WA', 6, '6 11 2019');
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id, post_date) VALUES ('New Grill', 18, 'newgrill.png', 13, true, 'Redmond, WA', 6, '7 11 2019');
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id, post_date) VALUES ('Mini Grill', 12, 'minigrill.png', 13, true, 'Redmond, WA', 6, '8 11 2019');
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id, post_date) VALUES ('Grilling', 20, 'grilling.png', 13, true, 'Redmond, WA', 6, '9 11 2019');
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id, post_date) VALUES ('Two Grills', 20, 'twogrills.png', 13, true, 'Redmond, WA', 6, '10 11 2019');
INSERT INTO fint.user (name, password, username) VALUES ('Tristan', 'TristanPassword', 'TristanUsername');
INSERT INTO fint.user (name, password, username) VALUES ('Jasper', 'JasperPassword', 'JasperUsername');
INSERT INTO fint.user (name, password, username) VALUES ('Matthew', 'MatthewPassword', 'MatthewUsername');
INSERT INTO fint.user (name, password, username) VALUES ('Louie', 'LouiePassword', 'LouieUsername');