INSERT INTO fint.user (name, password, username, location) VALUES ('Kyle Boxeth', 'KylePassword', 'KyleUsername', 'Ann Arbor, MI');
INSERT INTO fint.user (name, password, username, location) VALUES ('Jason Shin', 'JasonPassword', 'JasonUsername', 'Cleveland, OH');
INSERT INTO fint.user (name, password, username, location) VALUES ('Jess Kwok', 'JessPassword', 'JessUsername', 'Akron, OH');
INSERT INTO fint.user (name, password, username, location) VALUES ('Tristan Greiner', 'TristanPassword', 'TristanUsername', 'Seattle, WA');
INSERT INTO fint.user (name, password, username, location) VALUES ('Jasper Lee', 'JasperPassword', 'JasperUsername', 'Redmond, WA');
INSERT INTO fint.user (name, password, username, location) VALUES ('Matthew Kwok', 'MatthewPassword', 'MatthewUsername', 'Saline, MI');
INSERT INTO fint.user (name, password, username, location) VALUES ('Louie Tran', 'LouiePassword', 'LouieUsername', 'New York, NY');

INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id) VALUES ('Tuxedo', 20, 'tuxedo.png', 3, true, 'Ann Arbor, MI', 1);
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id) VALUES ('Car', 300, 'car.png', 120, false, 'Akron, OH', 3);
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id) VALUES ('Basketball', 5, 'bball.png', 15, true, 'Seattle, WA', 4);
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id, post_date) VALUES ('Grill', 1000, 'grill.png', 13, true, 'Redmond, WA', 5, '12 11 2019');
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id) VALUES ('Tractor', 276, 'tractor.png', 1, true, 'Saline, MI', 6);
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id) VALUES ('Board Game', 10, 'boardgame.jpg', 12, true, 'Ann Arbor, MI', 1);
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id) VALUES ('Bounce House', 300, 'bouncyhouse.jpg', 7, true, 'Ann Arbor, MI', 1);
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id) VALUES ('Camera', 45, 'camera.jpg', 18, true, 'Ann Arbor, MI', 1);
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id) VALUES ('Chainsaw', 50, 'chainsaw.jpg', 27, true, 'Ann Arbor, MI', 1);
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id) VALUES ('Chalkboard', 5, 'chalkboard.jpg', 33, true, 'Ann Arbor, MI', 1);
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id) VALUES ('Exercise Ball', 10, 'exerciseball.jpg', 120, true, 'Ann Arbor, MI', 1);
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id) VALUES ('Fishing Rod', 20, 'fishingrod.jpeg', 24, true, 'Ann Arbor, MI', 1);
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id) VALUES ('Ice Skates', 40, 'iceskates.jpeg', 72, true, 'Ann Arbor, MI', 1);
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id) VALUES ('Kayak', 100, 'kayak.jpeg', 18, true, 'Ann Arbor, MI', 1);
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id) VALUES ('Microphone', 20, 'mic.jpg', 89, true, 'Ann Arbor, MI', 1);
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id) VALUES ('Suitcase', 15, 'suitcase.jpg', 95, true, 'Ann Arbor, MI', 1);
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id) VALUES ('Tent', 50, 'tent.jpg', 30, true, 'Ann Arbor, MI', 1);
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id) VALUES ('Wedding Dress', 200, 'weddingdress.jpg', 10, true, 'Ann Arbor, MI', 1);
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id, post_date) VALUES ('Grill and Tool', 20, 'grill.png', 13, true, 'Redmond, WA', 5, '3-11-2019');
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id, post_date) VALUES ('Grill and Charcoal', 25, 'grill.png', 13, true, 'Redmond, WA', 5, '4-11-2019');
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id, post_date) VALUES ('Grill Brush', 5, 'grill.png', 13, true, 'Redmond, WA', 5, '5-11-2019');
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id, post_date) VALUES ('Grill Cover', 6, 'grill.png', 13, true, 'Redmond, WA', 5, '6-11-2019');
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id, post_date) VALUES ('New Grill', 18, 'grill.png', 13, true, 'Redmond, WA', 5, '7-11-2019');
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id, post_date) VALUES ('Mini Grill', 12, 'grill.png', 13, true, 'Redmond, WA', 5, '8-11-2019');
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id, post_date) VALUES ('Grilling', 20, 'grill.png', 13, true, 'Redmond, WA', 5, '9-11-2019');
INSERT INTO fint.item (name, price, picture, fint_count, is_available, location, finter_id, post_date) VALUES ('Two Grills', 20, 'grill.png', 13, true, 'Redmond, WA', 5, '10-11-2019');

INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (1, 2, 'This tuxedo is awesome', 4, '11-7-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (1, 3, 'This tuxedo is terrible', 1, '11-7-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (2, 7, 'This car smells new', 5, '11-7-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (2, 4, 'This car smells like trash', 1, '10-17-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (3, 5, 'This basketball is nice', 4, '4-7-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (4, 3, 'This grill is so dirty', 1, '5-7-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (4, 6, 'This grill is really heavy', 1, '6-18-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (5, 7, 'This tractor does the job', 5, '8-7-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (6, 3, 'This board game is so fun!', 5, '11-7-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (7, 3, 'This bounce house was a lot of fun', 5, '6-7-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (7, 4, 'This bounce house had a hole', 1, '7-17-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (8, 3, 'This camera takes really nice photos', 5, '12-1-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (9, 6, 'This chainsaw is broken', 1, '12-1-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (10, 5, 'This chalkboard is not clean', 1, '9-27-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (11, 6, 'This exercise ball smells like BO', 1, '5-11-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (12, 3, 'This fishing rod casts smoothly', 5, '7-18-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (13, 5, 'These ice skates are nice but need to be sharpened', 3, '1-27-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (14, 3, 'This kayak is super compact', 5, '8-28-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (15, 6, 'This microphone was super useful', 5, '11-7-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (16, 3, 'This suitcase is easy to use', 5, '11-17-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (17, 5, 'This tent is nice and roomy', 4, '8-15-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (18, 6, 'This wedding dress was beautiful', 5, '5-22-2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (19, 3, 'This grill and tool is good', 4, '1 11 2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (20, 3, 'Comes with lots of charcoal', 5, '1 11 2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (21, 3, 'Brush cleaned well', 3, '1 11 2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (22, 3, 'Cover kept food warm', 4, '1 11 2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (23, 3, 'Grill was not new', 1, '1 11 2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (24, 3, 'Broke', 2, '1 11 2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (25, 3, 'grilling', 3, '1 11 2019');
INSERT INTO fint.item_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (26, 3, 'twogrills', 2, '1 11 2019');

INSERT INTO fint.transaction (item_id, is_returned, fintee_id, start_date, end_date, t_price) VALUES (1, true, 2, '12-1-2019', '12-7-2019', 100);
INSERT INTO fint.transaction (item_id, is_returned, fintee_id, start_date, end_date, t_price) VALUES (1, true, 3, '11-1-2019', '11-7-2019', 100);
INSERT INTO fint.transaction (item_id, is_returned, fintee_id, start_date, end_date, t_price) VALUES (1, false, 4, '11-8-2019', '11-14-2019', 100);
INSERT INTO fint.transaction (item_id, is_returned, fintee_id, start_date, end_date, t_price) VALUES (2, false, 1, '12-1-2019', '12-7-2019', 100);
INSERT INTO fint.transaction (item_id, is_returned, fintee_id, start_date, end_date, t_price) VALUES (2, true, 1, '11-1-2019', '11-7-2019', 100);
INSERT INTO fint.transaction (item_id, is_returned, fintee_id, start_date, end_date, t_price) VALUES (6, true, 3, '11-1-2019', '11-7-2019', 100);
INSERT INTO fint.transaction (item_id, is_returned, fintee_id, start_date, end_date, t_price) VALUES (7, true, 3, '11-1-2019', '11-7-2019', 100);
INSERT INTO fint.transaction (item_id, is_returned, fintee_id, start_date, end_date, t_price) VALUES (8, true, 3, '11-1-2019', '11-7-2019', 100);
INSERT INTO fint.transaction (item_id, is_returned, fintee_id, start_date, end_date, t_price) VALUES (9, true, 3, '11-1-2019', '11-7-2019', 100);
INSERT INTO fint.transaction (item_id, is_returned, fintee_id, start_date, end_date, t_price) VALUES (10, true, 3, '11-1-2019', '11-7-2019', 100);
INSERT INTO fint.transaction (item_id, is_returned, fintee_id, start_date, end_date, t_price) VALUES (11, true, 3, '11-1-2019', '11-7-2019', 100);
INSERT INTO fint.transaction (item_id, is_returned, fintee_id, start_date, end_date, t_price) VALUES (12, true, 3, '11-1-2019', '11-7-2019', 100);
INSERT INTO fint.transaction (item_id, is_returned, fintee_id, start_date, end_date, t_price) VALUES (13, true, 3, '11-1-2019', '11-7-2019', 100);
INSERT INTO fint.transaction (item_id, is_returned, fintee_id, start_date, end_date, t_price) VALUES (14, true, 3, '11-1-2019', '11-7-2019', 100);
INSERT INTO fint.transaction (item_id, is_returned, fintee_id, start_date, end_date, t_price) VALUES (15, true, 3, '11-1-2019', '11-7-2019', 100);
INSERT INTO fint.transaction (item_id, is_returned, fintee_id, start_date, end_date, t_price) VALUES (16, true, 3, '11-1-2019', '11-7-2019', 100);
INSERT INTO fint.transaction (item_id, is_returned, fintee_id, start_date, end_date, t_price) VALUES (17, true, 3, '11-1-2019', '11-7-2019', 100);
INSERT INTO fint.transaction (item_id, is_returned, fintee_id, start_date, end_date, t_price) VALUES (18, true, 3, '11-1-2019', '11-7-2019', 100);

INSERT INTO fint.cart_item (item_id, fintee_id, start_date, end_date, price) VALUES (1, 1, '11-7-2019', '11-14-2019', 100);
INSERT INTO fint.cart_item (item_id, fintee_id, start_date, end_date, price) VALUES (2, 1, '11-7-2019', '11-14-2019', 50);

INSERT INTO fint.fintee_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (1, 2, 'Kyle is cool!', 4, '11-7-2019');
INSERT INTO fint.fintee_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (1, 3, 'I hate kyle :(', 1, '11-7-2019');
INSERT INTO fint.fintee_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (2, 6, 'Jason is a good finter', 4, '11-11-2019');
INSERT INTO fint.fintee_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (3, 7, 'Jess has only 1 outfint', 1, '11-17-2019');
INSERT INTO fint.fintee_review (reviewed_id, reviewer_id, description, rating, post_date) VALUES (3, 4, 'Her one outfint car is great', 5, '11-18-2019');
